version: '3.8'

services:
  gitea:
    extra_hosts:
      - "ci.eadn.dz:192.168.33.72"
      - "git.eadn.dz:192.168.33.72" 
    image: gitea/gitea:latest
    environment:
      USER_UID: 1000
      USER_GID: 1000
      DB_TYPE: postgres
      DB_HOST: postgres:5432
      DB_NAME: giteadb
      DB_USER: admin  
      DB_PASSWD: admin
      GITEA__server__ROOT_URL: http://git.eadn.dz/
      GITEA__server__SSH_DOMAIN: git.eadn.dz
      GITEA__server__SSH_PORT: 22
      GITEA__server__HTTP_PORT: 3000
      GITEA__webhook__ALLOWED_HOST_LIST: jenkins, jenkins:8080, localhost:8080, ci.eadn.dz
    ports:
       #- target: 3000
        # published: 3000
        # protocol: tcp
         #mode: host
       - target: 22
         published: 2222
         protocol: tcp
         mode: host
    volumes: 
      - gitea_data:/data
    networks:
      - gitea_db_net
      - devops_net
    deploy:
      replicas: 1
      restart_policy:
        condition: any

volumes:
  gitea_data:




networks:
  gitea_db_net:
    external: true #stack auto#
  devops_net:
    external: true
