version: '3.8'

services:
  app:
    image: app:1.0
    networks:
      - devops_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  devops_net:
    external: true