version: '3.8'

services:
  app:
    image: localhost:5000/eadn-repo/app:latest
    networks:
      - devops_net
    deploy:
      replicas: 1
      restart_policy:
        condition: any

networks:
  devops_net:
    external: true