version: '3.8'

services:
  jenkins:
    extra_hosts:
     - "git.eadn.dz:192.168.33.141"
     - "ci.eadn.dz:192.168.33.141"
    image: jenkins/jenkins:lts
    user: root
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - devops_net
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

volumes:
  jenkins_home:

networks:
  devops_net:
    external: true
